### PR TITLE
fixes #2531  value type on function overload

### LINKED ISSUE #2531: (simulate|write)Contract payable value not working for overloads
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.17.11

### Current Behavior

If an overloaded function has nonpayable and payable overloads, `simulateContract` and `writeContract`'s `value` parameter is not inferred correctly for the payable overload.

### Expected Behavior

Payable overload should allow `value` property.

### Steps To Reproduce

_No response_

### Link to Minimal Reproducible Example

https://www.typescriptlang.org/play/?target=99#code/JYWwDg9gTgLgBAbzgYygUwIYzQdQwG3zRgGF9g0A7GAGjgAsYYw6wMoBnNAQQCNg4AXzgAzKBBBwA5ADcKIKXAD0SuDACeYNBwBccAEwA6AIwB2E8YBQoSLERwA7lGDYSEalAzJacDqACu+Fhobh5e8MJiEtJyaCBK4cDuHIoqapraekZmFtbg0PBIIBjAlJTEQqLikrLySsj0JZQpyqoaWroGJubGVpbIyfDI5FTwALwo6MF4hMRkFNQAFAiWcHBeA-7UelIADAAeUjSrKI2lesWl5bQnMJ7NtjB6jMyLAJTHgm-9g+v8cBM2JwePxFgBtE5SERbbxJSi+DAiNAAFXuHCRUAAYtVFhgACZ49AcDh0fGE7QkuD+UowfQAVgAbG8jpDoZRYe4EUjURhmhjsRJcQSiZSySK6NTqPSGXReOpsBw3nA2OoMLwiCyALrfSxOFwhdx3cKLYYLHwrNZiik7A4sy38Y5rNkcygAOQwIDQOw4iJRaP51Tt6ygAHNOmC9vtDNGjtIDtHDLHjLtdpRNY7WnAAAIwDgAWjQ+y03gLUHEUBOMgI-i9cGMlE+3z1rkNnm8JpG1DoFvWwutccOGbVwAzzpgcPdnu9vp5fLQWMDQ9D4cjCdjq5jdGTqboG8T6cr1dr9cblksfhAgWCoSN7dNo27JytxJtg6fDpOY4nHtrUh93P9ecBQUJcwz0CN403Ac1y3FM0wzNIc3zQtixgUty0PfAaz0E9LC+c8AiCFswjvTtzSfPsXwHINh1HGFx3cSdf3-P1eXRIDFyfZdwL3ddIMTWCd2gmMDzWKssOPBs8O+IA

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Yuripetusko**
fixes #2531  - infer correct type of `value` on function overload, by matching correct function signature from a union type, given the function args

---

## PR-Codex overview
This PR focuses on improving type inference for function values in contracts. 

### Detailed summary
- Added type definitions for `GetMutabilityAwareValue` and `SimulateContractParameters` in `simulateContract.ts`
- Updated imports and types in `simulateContract.ts` and `writeContract.ts`
- Fixed issue #2560 related to function overloads in `simulateContract.test-d.ts`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by jxom — APPROVED** [review]
Looks fine to me. Would be good to get @tmm eyes on it too!

File: src/types/contract.ts [hunk 1]
```diff
@@ -303,10 +303,19 @@ export type EventDefinition = `${string}(${string})`
 
 export type GetValue<
   abi extends Abi | readonly unknown[],
-  functionName extends string,
+  mutability extends AbiStateMutability = AbiStateMutability,
```
Comment (Yuripetusko) [inline src/types/contract.ts:306]: Ideally mutability should be inferred. Also it sucks that it's a second argument of this Generic (because subsequent arguments require it), as it makes it hard to skip it if you don't want to pass it

File: test/src/abis.ts [hunk 2]
```diff
@@ -1363,6 +1363,16 @@ export const wagmiContractConfig = {
       stateMutability: 'nonpayable',
       type: 'function',
     },
+    {
```
Comment (Yuripetusko) [inline test/src/abis.ts:1366]: I see that this config has a contract address, do I need to add this function to the actual contract? or it's fine to just have this dummy/placeholder abi for a contract that is not actually deployed?

**Comment by tmm** [comment]
Will take a look tomorrow!

**Comment by Yuripetusko** [comment]
> Will take a look tomorrow!

bump

File: src/types/contract.ts (hunk 1 above)
Comment (tmm) [reply src/types/contract.ts:306]: Since `GetValue` is a public API (exported in `index.ts`), let's pull this logic directly into `simulateContract.ts` for now.

File: test/src/abis.ts (hunk 2 above)
Comment (tmm) [reply test/src/abis.ts:1366]: Let's remove this addition to the ABI.

File: src/types/contract.test-d.ts
Comment (tmm) [inline src/types/contract.test-d.ts:1]: Let's revert this change.

**Review by tmm — CHANGES_REQUESTED** [review]
Let's revert the change to `GetValue` and update `SimulateContractParameters` directly with this logic. Also, let's add the following test. (Haven't found a quick way to get `@ts-expect-error` to work correctly in this case so might be best to remove that for now. There's a larger type refactor coming to Viem, which will fix this so allowing it to pass for the time being isn't the end of the world.)

```ts
test('https://github.com/wevm/viem/issues/2531', async () => {
  const abi = parseAbi([
    'function safeTransferFrom(address, address, uint256)',
    'function safeTransferFrom(address, address, uint256, bytes) payable',
  ])

  const res1 = await simulateContract(client, {
    address: '0x',
    abi,
    functionName: 'safeTransferFrom',
    args: ['0x', '0x', 123n],
    // @ts-expect-error
    value: 123n,
  })
  assertType<void>(res1.result)
  expectTypeOf(res1.request.abi).toEqualTypeOf(
    parseAbi(['function safeTransferFrom(address, address, uint256)']),
  )

  const res2 = await simulateContract(client, {
    address: '0x',
    abi,
    functionName: 'safeTransferFrom',
    args: ['0x', '0x', 123n, '0x'],
    value: 123n,
  })
  assertType<void>(res2.result)
  expectTypeOf(res2.request.abi).toEqualTypeOf(
    parseAbi([
      'function safeTransferFrom(address, address, uint256, bytes) payable',
    ]),
  )
})
```

In summary:
- Remove `GetValue` related changes
- Add logic directly to `SimulateContractParameters`
- Add test to `simulateContract.test-d.ts`

**Comment by Yuripetusko** [comment]
> Let's revert the change to `GetValue` and update `SimulateContractParameters` directly with this logic. Also, let's add the following test. (Haven't found a quick way to get `@ts-expect-error` to work correctly in this case so might be best to remove that for now. There's a larger type refactor coming to Viem, which will fix this so allowing it to pass for the time being isn't the end of the world.)
> 
> ```ts
> test('https://github.com/wevm/viem/issues/2531', async () => {
>   const abi = parseAbi([
>     'function safeTransferFrom(address, address, uint256)',
>     'function safeTransferFrom(address, address, uint256, bytes) payable',
>   ])
> 
>   const res1 = await simulateContract(client, {
>     address: '0x',
>     abi,
>     functionName: 'safeTransferFrom',
>     args: ['0x', '0x', 123n],
>     // @ts-expect-error
>     value: 123n,
>   })
>   assertType<void>(res1.result)
>   expectTypeOf(res1.request.abi).toEqualTypeOf(
>     parseAbi(['function safeTransferFrom(address, address, uint256)']),
>   )
> 
>   const res2 = await simulateContract(client, {
>     address: '0x',
>     abi,
>     functionName: 'safeTransferFrom',
>     args: ['0x', '0x', 123n, '0x'],
>     value: 123n,
>   })
>   assertType<void>(res2.result)
>   expectTypeOf(res2.request.abi).toEqualTypeOf(
>     parseAbi([
>       'function safeTransferFrom(address, address, uint256, bytes) payable',
>     ]),
>   )
> })
> ```
> 
> In summary:
> 
> * Remove `GetValue` related changes
> * Add logic directly to `SimulateContractParameters`
> * Add test to `simulateContract.test-d.ts`

Hm the reason ts-expect-error doesn't do anything here is that parseAi only picks one of the mutability options when merging an overload

image

**Comment by tmm** [comment]
@Yuripetusko nice find. Can drop `parseAbi` and add the object directly instead.

**Comment by Yuripetusko** [comment]
> @Yuripetusko nice find. Can drop `parseAbi` and add the object directly instead.

Weirdly I can't reproduce this in here. So maybe it's my Jetbrains IDE messing with me again

https://stackblitz.com/edit/viem-getting-started-jixksa?file=package.json,index.ts

**Comment by Yuripetusko** [comment]
@tmm added it to writeContract too, but lmk if I should just add it to simulateContract. Unfortunately I keep getting http errors when running all tests locally. But selected tests seems to be fine. Ignore the previous comments about parseAbi, it was due to something else entirely (missing `args` on new Generic, which is required to find the correct function in case of overloads)

File: .changeset/new-hotels-sell.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"viem": patch
+---
+
+fixes #2560: infer the correct `value` type on function overload by matching correct function using function args
```
Comment (tmm) [inline .changeset/new-hotels-sell.md:5]:
```suggestion
Fixed #2560: infer the correct payable `value` type on function overloads by matching function against `args`.
```

**Review by tmm — APPROVED** [review]
