### PR TITLE
fix: writeContract args type inference

### LINKED ISSUE #1655: bug: args typing regression
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.3

### Current Behavior

since `2.0.0`, `args` property type is inferred to `unknown[]` instead of the correct type.

### Expected Behavior

`args` should be inferred to `[number]` in provided example.

It works properly in version `1.21.4`

### Steps To Reproduce

_No response_

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-nnlghk?file=index.ts

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tmm**
Closes #1655

---

### Focus of the PR:
Fixing type inference for the `args` parameter in the `writeContract` function.

### Detailed summary:
- Fixed type inference for the `args` parameter in the `writeContract` function.
- Added type checks for `args` in the `CheckArgs` type.
- Added test cases for `WriteContractParameters` and overloads.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

File: src/types/contract.ts
Comment (tmm) [inline src/types/contract.ts:1]: simplified this

File: src/types/contract.test-d.ts
Comment (tmm) [inline src/types/contract.test-d.ts:1]: added another test

File: src/actions/wallet/writeContract.ts [hunk 1]
```diff
@@ -136,7 +136,11 @@ export async function writeContract<
   account extends Account | undefined,
   const abi extends Abi | readonly unknown[],
   functionName extends ContractFunctionName<abi, 'nonpayable' | 'payable'>,
-  args extends ContractFunctionArgs<abi, 'pure' | 'view', functionName>,
```
Comment (tmm) [inline src/actions/wallet/writeContract.ts:139]: was targeting the wrong state mutability 🤦‍♂️ (added some type tests to make sure we catch this next time)

File: src/actions/wallet/writeContract.test-d.ts
Comment (tmm) [inline src/actions/wallet/writeContract.test-d.ts:1]: boosting type test coverage
